name: girlcode
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9.*
  - ipykernel
  - ipywidgets
  - pandas
  - numpy
  - matplotlib
  - altair
  - requests
  - scipy
  - pip
  - pip:
      - flask
      - mlxtend
      - selenium
